ChallengeNaStaz/Controllers/DietsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChallengeNaStaz.Data;
using ChallengeNaStaz.Models;
using ChallengeNaStaz.Extensions;

namespace ChallengeNaStaz.Controllers
{
    //[Route("[controller]/[action]")]
    public class DietsController : Controller
    {
        private readonly ApplicationDbContext context;

        public DietsController(ApplicationDbContext context)
        {
            this.context = context;
        }

        //webapi - uzyte w widoku Diets/Index
        [HttpGet]
        public IActionResult GetDiets(string queryString)
        {
            Console.WriteLine(queryString);

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            List<Diet> diets = new List<Diet>();
            if (!String.IsNullOrEmpty(queryString))
            {
                diets = context.Diets.Where(d => d.DietName.Contains(queryString)).Include(d => d.DietMeals).Include(d => d.Patients).ToList();
            }
            else
            {
                diets = context.Diets.Include(d => d.DietMeals).Include(d => d.Patients).ToList();
            }
            var json = Json(diets);
            return Json(diets);
        }

        //webapi - użyte w widoku Diets/Create
        ///todo - dodać sprawdzanie błędów, teraz metoda zawsze zróci kod ok
        /*[HttpPost]
        public IActionResult PostDiet([FromBody]DietPostModel diet)
        {
            //tworzy diete
            Diet d = new Diet();
            d.IdealForPatients = "TestKontrolera";
            d.DietName = diet.Name;

            //zapisuje
            context.Diets.Add(d);
            context.SaveChanges();

            //pobiera tą diete tak by miała id
            var retrievedDiet = context.Diets.Where(qdiet => qdiet.DietName == d.DietName).First();

            //tworzy join entity który złączy istniejącą diete z istniejącymi posiłkami
            List<DietMeal> join = new List<DietMeal>(diet.MealIds.Count);
            foreach (var mealID in diet.MealIds)
            {
                join.Add(new DietMeal { DietId = retrievedDiet.DietID, MealId = mealID });
            }

            //dodaje zapisuje
            context.DietMeals.AddRange(join);
            context.SaveChanges();

            return Ok();
        }*/

        // GET: Diets
        public async Task<IActionResult> Index()
        {
            /*if (TempData.ContainsKey("MSG"))
            {
                TempData.Add("MSG", new Tuple<int, string>(1, "Pomyślnie usunięto dietę"));
            }*/

            var list = await context.Diets
                .Include(d => d.DietMeals)
                .Include(d => d.Patients).ToListAsync();
            return View(list);
        }

        // GET: Diets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Diets1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DietRaw rawDiet) //wzorcowy
        {
            if (ModelState.IsValid)
            {
                Diet diet = new Diet
                {
                    DietName = rawDiet.DietName
                };
                context.Diets.Add(diet);
                await context.SaveChangesAsync();

                List<DietMeal> relation = new List<DietMeal>();
                for (int i = 0; i < rawDiet.Meals.Count; i++)
                {
                    relation.Add(new DietMeal()
                    {
                        DietId = diet.DietID,
                        MealId = rawDiet.Meals.ElementAt(i)
                    });
                }
                diet.IdealForPatients = rawDiet.IdealFor;
                diet.DietMeals = relation;

                await context.SaveChangesAsync();
                TempData.AddAlert(AlertType.Success, "Poprawnie utworzono dietę");
            }
            return RedirectToAction(nameof(Index));
            //return View(diet);
        }

        // GET: Diets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var diet = await context.Diets.Where(m => m.DietID == id).Include(m => m.DietMeals).FirstAsync();
            var diet = await context.Diets
                .Where(m => m.DietID == id)
                .Include(d => d.DietMeals)
                    .ThenInclude(dm => dm.Meal)
                .FirstAsync();
            if (diet == null)
            {
                return NotFound();
            }
            return View(diet);
        }

        // POST: Diets/Manage/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DietRaw diet)
        {
            var td = await context.Diets.Where(dd => dd.DietID == id).Include(d => d.DietMeals).ThenInclude(dm => dm.Meal).FirstAsync();
            if (td == null)
            {
                return NotFound();
            }
            td.DietMeals.Clear();
            //gdy nie zapiszemy tutaj posypie sie entity tracking, coś z duplikowaniem entity
            await context.SaveChangesAsync();

            td.IdealForPatients = diet.IdealFor;
            td.DietName = diet.DietName;
            foreach (var mealID in diet.Meals)
            {
                td.DietMeals.Add(new DietMeal()
                {
                    DietId = id,
                    MealId = mealID,
                });
            }


            if (ModelState.IsValid)
            {
                try
                {
                    await context.SaveChangesAsync();
                    TempData.AddAlert(AlertType.Success, "Poprawnie zaktualizowano dietę");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (context.Diets.Where(d => d.DietID == id).First() != null)
                    {
                        TempData.AddAlert(AlertType.Warning, "Próba edycji nieistniejącej diety!", "BŁĄD");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(diet);
        }

        public IActionResult ConfirmDelete(int id)
        {
            var o = context.Diets.SingleOrDefault(d => d.DietID == id);
            context.Remove(o);
            context.SaveChanges();
            TempData.AddAlert(AlertType.Success, "Usunięto"/*, "Usuwanie diety"*/);
            return RedirectToAction(nameof(Index));
        }
    }
}

ChallengeNaStaz/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChallengeNaStaz.Data;
using ChallengeNaStaz.Models;

namespace ChallengeNaStaz.Controllers
{
    //todo dodać alerty
    //todo dodać zarzadzanie
    //[Route("[controller]/[action]")]
    public class MealsController : Controller
    {
        private readonly ApplicationDbContext _context;

        //webapi - użyte w widoku Meals/Index
        //[HttpGet]
        public async Task<IActionResult> GetMeals([FromQuery] string queryString)
        {
            Console.WriteLine(queryString);

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            List<Meal> meals = new List<Meal>();
            if (!String.IsNullOrEmpty(queryString))
            {
                meals = await _context.Meals.Where(m => m.MealName.Contains(queryString)).ToListAsync();
            }
            else
            {
                meals = await _context.Meals.ToListAsync();
            }

            return Ok(meals);
        }

        //webapi
        /*[HttpGet("{id}")]
        public async Task<IActionResult> GetMeal([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var meal = await _context.Meals.SingleOrDefaultAsync(m => m.MealId == id);

            if (meal == null)
            {
                return NotFound();
            }

            return Ok(meal);
        }
        */
        //uzyte do pobrania view component z listą posiłków
        [HttpPost]
        public ActionResult FindMeals([FromBody]SearchWithMask query)
        {
            return ViewComponent("MealList", query);
        }

        //webapi - aktualizuje posiłek, użyte w widoku Diet/Create
        [HttpPut]
        public async Task<IActionResult> PutMeal([FromBody]MealPostModel updatedMeal)
        {
            //Meal temp = new Meal { MealId = mealId, Recipe = recipe, ShoppingList = shoppingList };
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            Meal meal = _context.Meals.Where(m => m.MealId == updatedMeal.Id).First();
            meal.Recipe = updatedMeal.Recipe;
            meal.ShoppingList = updatedMeal.ShoppingList;

            //_context.Entry(temp).State = EntityState.Modified;
            _context.Meals.Update(meal);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MealExists(meal.MealId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        public MealsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Meals1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Meals.ToListAsync());
        }

        // GET: Meals1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals
                .SingleOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // GET: Meals1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meals1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MealId,MealName,Recipe,ShoppingList")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: Meals1/Edit/5
        //[Route("{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals.SingleOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }
            return View(meal);
        }

        // POST: Meals1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MealId,MealName,Recipe,ShoppingList")] Meal meal)
        {
            if (id != meal.MealId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealExists(meal.MealId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: Meals1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals
                .SingleOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // POST: Meals1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meal = await _context.Meals.SingleOrDefaultAsync(m => m.MealId == id);
            _context.Meals.Remove(meal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MealExists(int id)
        {
            return _context.Meals.Any(e => e.MealId == id);
        }
    }
}

ChallengeNaStaz/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChallengeNaStaz.Data;
using ChallengeNaStaz.Models;
using Microsoft.AspNetCore.Identity;
using ChallengeNaStaz.Models.UserViewModels;

namespace ChallengeNaStaz.Controllers
{
    //todo dodać alerty
    //todo dodać zarzadzanie
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public UsersController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,  ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _userManager.GetUsersInRoleAsync("Nutritionist"));
        }

        // GET: Users/Create
        //Zakładanie konta dietetyka
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewUserViewModel applicationUser)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser {
                    UserName = applicationUser.Email,
                    Email = applicationUser.Email,
                    SecurityStamp = Guid.NewGuid().ToString()
                };

                //posypie sie jeśli hasło bedzie za słabe
                await _userManager.CreateAsync(user, applicationUser.Password);
                var retrievedUser = await _userManager.FindByNameAsync(user.UserName);

                await _userManager.AddToRoleAsync(retrievedUser, "Nutritionist");

                //await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = _userManager.FindByIdAsync(id);

            await _userManager.DeleteAsync(user.Result);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _userManager.FindByIdAsync(id) != null;
        }
    }
}

ChallengeNaStaz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChallengeNaStaz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <!--<environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>-->
</head>
@using ChallengeNaStaz.Extensions;
<body>
    <environment include="Development">
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)

    <div class="container">
        @await Html.PartialAsync("_LoginPartial")

        <!--nav-->
        <div class="row">
            <div class="col col-12">
                <nav>
                    <ul>
                        <li>
                            <div>
                                <img src="~/images/icons/nav/diet_128x128.png" />
                                <br />
                                <a asp-action="Index" asp-controller="Diets">Diety</a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="~/images/icons/nav/patient_128x128.png" />
                                <a asp-action="Index" asp-controller="Patients">Pacjenci</a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="~/images/icons/nav/nutritionist_128x128.png" />
                                <a asp-action="Index" asp-controller="Users">Dietetycy</a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="~/images/icons/nav/meal_128x128.png" />
                                <a asp-action="Index" asp-controller="Meals">Posiłki</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--alert bar-->
        <div class="row">
            <div class="col">

            </div>
        </div>
        @{
        var alerts = TempData.GetAlerts();
        if (alerts.Count > 0)
        {
            <div class="row">
                @foreach (Alert alert in alerts)
                {
                    <div class="col">
                        @await Component.InvokeAsync("Alert", alert)
                    </div>
                }
            </div>
        }
        }
        <hr class="mt-0" />
        <!--body-->
        <div class="row">
            <div class="col col-12 ">
                @RenderBody()
            </div>
        </div>
        <footer class="row">
            <p class="col">&copy; 2017 - ChallengeNaStaz</p>
        </footer>
    </div>
</body>
</html>